service: petrolappapi

provider:
 name: aws
 runtime: nodejs10.x
 memorySize: 128
 timeout: 10
 stage: production
 region: eu-west-2

functions:
  api:
    handler: lambda.universal
    events:
      - http: ANY {proxy+}
      - http: ANY /